name: BanSystem
version: 3.2
author: Tobias Herzig
main: net.coalcube.bansystem.spigot.BanSystemSpigot
commands:
  ban:
  unban:
  unmute:
  bansystem:
  bansys:
  kick:
  history:
    aliases: [hist]
  check:
  deletehistory:
  delhistory: